version: '3.8'
services:
  prometheus-01: &prometheus
    image: prom/prometheus:v2.24.1
    container_name: prometheus-01
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--web.external-url=http://localhost/prometheus",
        "--web.route-prefix=/",
      ]
    volumes:
      [
        "./deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml",
        "./deployment/prometheus/rules.yml:/etc/prometheus/rules.yml",
      ]
  prometheus-02:
    <<: *prometheus
    container_name: prometheus-02
  prometheus-03:
    <<: *prometheus
    container_name: prometheus-03
  alertmanager-01: &alertmanager 
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager-01
    command:
      [
        "--config.file=/etc/alertmanager/alertmanager.yml",
        "--web.external-url=http://localhost/alertmanager",
        "--web.route-prefix=/",
        "--cluster.peer=alertmanager-02:9094",
        "--cluster.peer=alertmanager-03:9094",
      ]
    volumes:
      [
        "./deployment/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml",
      ]
    ports:
      - 8093:9093
  alertmanager-02:
    <<: *alertmanager
    container_name: alertmanager-02
    command:
      [
        "--config.file=/etc/alertmanager/alertmanager.yml",
        "--web.external-url=http://localhost/alertmanager",
        "--web.route-prefix=/",
        "--cluster.peer=alertmanager-01:9094",
        "--cluster.peer=alertmanager-03:9094",
      ]
    ports:
      - 8094:9093
  alertmanager-03:
    <<: *alertmanager
    container_name: alertmanager-03
    command:
      [
        "--config.file=/etc/alertmanager/alertmanager.yml",
        "--web.external-url=http://localhost/alertmanager",
        "--web.route-prefix=/",
        "--cluster.peer=alertmanager-01:9094",
        "--cluster.peer=alertmanager-02:9094",
      ]
    ports:
      - 8095:9093
  grafana:
    image: grafana/grafana:7.3.7
    container_name: grafana
    volumes:
      [
        "./deployment/grafana/grafana.ini:/etc/grafana/grafana.ini",
        "./deployment/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml",
      ]
  nginx:
    image: nginx:1.18.0
    container_name: nginx
    volumes:
      [
        "./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf",
      ] 
    ports:
      - 80:80