global:
  scrape_interval:     10s
  evaluation_interval: 10s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
        [
          "alertmanager-01:9093",
          "alertmanager-02:9093",
          "alertmanager-03:9093",  
        ]
rule_files:
  - "rules.yml"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: 
        [
          "prometheus-01:9090",
          "prometheus-02:9090",
          "prometheus-03:9090",
        ]
  - job_name: "alertmanager"
    static_configs:
    - targets: 
        [
          "alertmanager-01:9093",
          "alertmanager-02:9093",
          "alertmanager-03:9093",  
        ]
  - job_name: "grafana"
    static_configs:
    - targets: ["grafana:3000"]